### ISSUE TITLE
Design the Home screen.

### ISSUE THREAD

**Issue by louiCoder** [louiCoder/Pamoja-Android#14]
- Make sure you follow the same mock up design that can be found [Here](https://app.zeplin.io/project/5cdc861696f9892aa0aa2860/screen/5cdc8b25308e3b1daac25f97)
- Icons for this component can be found on the same page. Please download and add the icons to the assets folder/directory.
- Use the createStackNavigator to create the bottom Menu.

**Comment by Albystein** [comment]
Correction please, it is createMaterialBottomNavigator or createBottomNavigator not createStackNavigator

**Comment by louiCoder** [comment]
> Correction please, it is createMaterialBottomNavigator or createBottomNavigator not createStackNavigator

Yes please, pardon me! FYI createBottomNavigator is deprecated

**Comment by Albystein** [comment]
sorry, I meant createBottomTabNavigator.
